version: '3.8'

services:
  sql-server:
    build: ./database
    environment:
      SA_PASSWORD: "123456"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    healthcheck:
      test: ["CMD", "/opt/mssql-tools/bin/sqlcmd", "-S", "localhost", "-U", "sa", "-P", "123456", "-Q", "SELECT 1"]
      interval: 5s
      timeout: 5s
      retries: 10

  k6:
    image: grafana/k6:latest
    volumes:
      - ./k6:/scripts
      - ./scripts:/python_scripts
    depends_on:
      sql-server:
        condition: service_healthy
    command: ["run", "/scripts/ecommerce_k6_load.js"]